name: surf_flutter_courses_template
description: Our courses' template.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0" # Dart SDK version
  flutter: 3.10.3 # Fixed Flutter version

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets\image\svg\image1.svg
    - assets/image/jpg/photo1.jpg
    - assets\image\jpg\photo2.jpg
    - assets\image\jpg\photo3.jpg
    - assets\image\jpg\photo4.jpg
    - assets\image\jpg\photo5.jpg
    - assets\image\jpg\photo6.jpg
    - assets\image\jpg\photo7.jpg
    - assets\image\jpg\photo8.jpg
    - assets\image\jpg\photo9.jpg
    - assets\image\image 1.png
